machine:
  php:
    version: 7.1.6
  timezone: Europe/Amsterdam
  environment:
    SYMFONY_ENV: test

dependencies:
  pre:
    # application
    - sudo composer self-update
    # selenium
    - wget http://selenium-release.storage.googleapis.com/3.4/selenium-server-standalone-3.4.0.jar
    - wget https://chromedriver.storage.googleapis.com/2.27/chromedriver_linux64.zip
    - unzip chromedriver_linux64.zip
    - "java -jar selenium-server-standalone-3.4.0.jar > /dev/null 2>&1":
              {background: true}

  post:

test:
  pre:
    # warmup and change permission of cache directory
    - bin/console d:d:c --if-not-exists
    - bin/console doctrine:schema:create  --no-interaction
    - bin/console doctrine:schema:validate --no-interaction
    - bin/console cache:clear --env=test --no-debug --no-warmup
    - chmod -R a+w var/cache
    # change permission of sessions directory
    - sudo chown -R www-data var/sessions
    - bin/console server:start

  override:
    # test command here

  post:
    - cp -r tests/_output $CIRCLE_ARTIFACTS

#deployment:
#  production:
#    branch: master
#    commands:
#      - ./deploy.sh production master
#
#  staging:
#    branch: deployer
#    commands:
#      - ./deploy.sh staging deployer

#  staging:
#    branch: master
#    commands:
#      - ./deploy_staging.sh